// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemaLaserAPI.Data;

#nullable disable

namespace sistemaLaserAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("sistemaLaserAPI.Models.Incident", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("counter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("detectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("deviceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("signalValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
